--selects all verified donor
Create or REPLACE VIEW VERIFIED_DONOR as
SELECT "EMAIL", "INSTITUTION_TYPE", "INSTITUTION_NAME", "PHONE",
       "DIVISION" || ', ' || "DISTRICT" || ', ' || "CITY" || ', ' || "STREETNO" AS "ADDRESS",
       "DATE_D"
FROM "ADMIN"."DONOR" where verified='Y';


select * from VERIFIED_DONOR;

-- selects all the VOLUNTEER from VOLUNTEER table
CREATE OR REPLACE VIEW VOLUNTEER_INFO AS
SELECT
    ROW_NUMBER() OVER (ORDER BY V.VOLUNTEER_ID) AS "No",
    V.NAME,
    V.EMAIL,
    V.DATE_OF_BIRTH AS "Date Of Birth",
    V.DIVISION || ', ' || V.DISTRICT || ', ' || V.CITY || ', ' || V.STREETNO AS "Address",
    V.PHONE
FROM
    VOLUNTEER V;
SELECT * FROM VOLUNTEER_INFO;




-- gives all info of RECIPIENT
CREATE OR REPLACE VIEW RECIPIENT_INFO AS
SELECT
    ROW_NUMBER() OVER (ORDER BY R.RECIPIENT_ID) AS "No",
    R.EMAIL,
    R.INSTITUTION_NAME,
    R.INSTITUTION_TYPE,
    R.NUMBER_OF_PEOPLE AS "Number Of People",
    R.DATE_R AS "Date"
FROM
    RECIPIENT R
WHERE
    R.VERIFIED = 'Y';

SELECT * from RECIPIENT_INFO;