CREATE TABLE "MAISHA"."SELLS" 
   (	"DONOR_ID" NUMBER, 
	"NID" NUMBER, 
	"FOOD_ID" NUMBER, 
	"ORIGINAL_PRICE" NUMBER, 
	"DISCOUNTED_PRICE" NUMBER, 
	"DATE_S" DATE, 
	 PRIMARY KEY ("DONOR_ID", "NID", "FOOD_ID")
  USING INDEX  ENABLE, 
	 FOREIGN KEY ("DONOR_ID")
	  REFERENCES "MAISHA"."DONOR" ("DONOR_ID") ENABLE, 
	 FOREIGN KEY ("NID")
	  REFERENCES "MAISHA"."CUSTOMER" ("NID") ENABLE, 
	 FOREIGN KEY ("FOOD_ID")
	  REFERENCES "MAISHA"."FOOD" ("FOOD_ID") ENABLE
   ) ;
